test: manual workflow

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -1,17 +1,46 @@
-name: deploy-dev
+# name: deploy-dev
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
+#   workflow_dispatch:
+#     inputs:
+#       tag:
+#         description: 'Tag to deploy'
+#         required: true
+#         type: string
+#         default: 'latest'
+#       container_update:
+#         description: 'Update container image'
+#         required: true
+#         type: boolean
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Deploy
-        run: |
-          echo 'deploying...'
-          sleep 5
-          echo '(fake) deploy is done!'
+# jobs:
+#   deploy:
+#     if: github.event_name != 'workflow_dispatch'
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: actions/checkout@v3
+#       - name: Deploy
+#         run: |
+#           echo 'deploying...'
+#           sleep 5
+#           echo '(fake) deploy is done!'
+  
+#   manual-deploy:
+#     if: github.event_name == 'workflow_dispatch'
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Fail if not authorised user
+#         if: github.event_name == 'workflow_dispatch' && !contains('["ocha-heidi"]', github.actor)
+#         run: |
+#           echo "Error: You are not authorised to do manual deploy"
+#           exit 1
+
+#       - uses: actions/checkout@v3
+#       - name: Deploy
+#         run: |
+#           echo 'deploying...'
+#           sleep 5
+#           echo '(fake) manual deploy is done!'
